micronaut:
  application:
    name: keymanagerGrpc

datasources:
  #default:
  #url: ${DATABASE_URL:`jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE`}
  #driverClassName: org.h2.Driver
  #username: ${DATABASE_USERNAME:sa}
  #password: ${DATABASE_PASSWORD:''}
  #schema-generate: CREATE_DROP
  #dialect: H2

  default:
    url: ${DATABASE_URL:`jdbc:mysql://localhost:3306/keymanager?createDatabaseIfNotExist=true`}
    #driverClassName: ${JDBC_DRIVER:`com.mysql.cj.jdbc.Driver`}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    schema-generate: CREATE_DROP

jpa.default.properties.hibernate.hbm2ddl.auto: update

itau:
  erp:
    server-url: 'http://localhost:9091'

bcb:
  pix:
    server-url: 'http://localhost:8082'
